# Generated by Django 6.0.5 on 2026-05-20 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input', models.TextField(blank=True, help_text='Free text project description from user', null=True)),
                ('uploaded_file', models.FileField(blank=True, help_text='Uploaded PDF/DOCX/TXT file', null=True, upload_to='uploads/')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from raw_input or uploaded_file', null=True)),
                ('clarification_questions', models.JSONField(blank=True, help_text='List of 3-5 clarifying questions from AI', null=True)),
                ('clarification_answers', models.JSONField(blank=True, help_text='User answers to clarification questions', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('clarifying', 'Generating Clarification Questions'), ('awaiting_answers', 'Awaiting User Answers'), ('generating_brd', 'Generating BRD'), ('awaiting_approval', 'Awaiting BRD Approval'), ('approved', 'BRD Approved — Running Remaining Agents'), ('complete', 'Complete'), ('failed', 'Failed')], default='new', max_length=50)),
                ('brd_approved', models.BooleanField(default=False)),
                ('revision_notes', models.TextField(blank=True, help_text='User notes when requesting a BRD revision', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('clarification', 'Clarification Agent'), ('brd', 'BRD Agent'), ('plan', 'Project Plan Agent'), ('test_cases', 'Test Case Agent'), ('effort', 'Effort Estimation Agent')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_output', models.TextField(blank=True, help_text='Raw AI response — fallback if JSON parsing fails', null=True)),
                ('structured_output', models.JSONField(blank=True, help_text='Parsed JSON output — what the frontend reads', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('project', 'agent_type')},
            },
        ),
    ]
