# Generated by Django 6.0.5 on 2026-05-29 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentoutput',
            options={'ordering': ['created_at'], 'verbose_name': 'Agent Output', 'verbose_name_plural': 'Agent Outputs'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='application_type',
            field=models.CharField(blank=True, choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('api', 'API / Microservice'), ('data', 'Data / Analytics Platform'), ('integration', 'Integration / Middleware'), ('desktop', 'Desktop Application'), ('other', 'Other')], help_text='Category of system being built', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, help_text='Requesting department e.g. "Finance" or "IT Operations"', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='line_of_business',
            field=models.CharField(blank=True, help_text='Line of business / business unit e.g. "Retail Banking"', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='Short project name e.g. "Customer Portal Redesign"', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('clarifying', 'Generating Clarification Questions'), ('awaiting_answers', 'Awaiting User Answers'), ('generating_brd', 'Generating BRD'), ('awaiting_approval', 'Awaiting BRD Approval'), ('approved', 'BRD Approved — Running Remaining Agents'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Primary project description file (PDF/DOCX/TXT)', null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_type', models.CharField(choices=[('mom', 'Minutes of Meeting'), ('url', 'Reference URL'), ('architecture', 'Architecture / Design Diagram'), ('document', 'Reference Document'), ('chat', 'Chat Export'), ('email', 'Email Thread'), ('recording', 'Call Recording Transcript')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='User-provided label for this asset', max_length=255, null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (MOM, PDF, DOCX, TXT, image for architecture)', null=True, upload_to='assets/')),
                ('url', models.URLField(blank=True, help_text='URL to scrape (used for url connector type)', max_length=2048, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from the source', null=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated concise summary injected into agent prompts', null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending Extraction'), ('processing', 'Extracting & Summarising'), ('complete', 'Ready'), ('failed', 'Extraction Failed')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='When True, this asset is injected into AI prompts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Asset',
                'verbose_name_plural': 'Project Assets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BRDVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Monotonically increasing version counter (1, 2, 3, ...)')),
                ('structured_output', models.JSONField(help_text='Full BRD JSON at the time of this snapshot')),
                ('notes', models.TextField(blank=True, help_text='Optional user notes about this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brd_versions', to='projects.project')),
            ],
            options={
                'verbose_name': 'BRD Version',
                'verbose_name_plural': 'BRD Versions',
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='TOCSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='JSON field key for standard sections, or slug for custom sections', max_length=100)),
                ('label', models.CharField(help_text='Human-readable section title displayed in the document', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Display order — lower numbers appear first')),
                ('is_enabled', models.BooleanField(default=True, help_text='When False, this section is hidden from the BRD output')),
                ('is_custom', models.BooleanField(default=False, help_text='True for user-added sections not in the standard 11')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc_sections', to='projects.project')),
            ],
            options={
                'verbose_name': 'TOC Section',
                'verbose_name_plural': 'TOC Sections',
                'ordering': ['order'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
