# Generated by Django 6.0.5 on 2026-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_assets_versions_toc_project_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_type',
            field=models.CharField(blank=True, choices=[('salesforce', 'Salesforce'), ('servicenow', 'ServiceNow'), ('sap', 'SAP'), ('custom', 'Custom Application')], help_text='Category of system being built', max_length=50, null=True),
        ),
    ]
