# Generated by Django 6.0.5 on 2026-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocsection',
            name='is_required',
            field=models.BooleanField(default=False, help_text='When True, the user cannot delete or disable this section'),
        ),
        migrations.AlterField(
            model_name='tocsection',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True for user-added sections not in the standard list'),
        ),
    ]
