# Generated by Django 6.0.5 on 2026-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tocsection_is_required_alter_tocsection_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_standalone',
            field=models.BooleanField(default=False, help_text='If True, indicates the project is created directly from an external BRD to generate downstream artifacts.'),
        ),
    ]
