# Generated by Django 6.0.5 on 2026-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectplanversion_testcaseversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='connector_type',
            field=models.CharField(choices=[('mom', 'Minutes of Meeting'), ('draft', 'Draft BRD Document'), ('url', 'Reference URL'), ('architecture', 'Architecture / Design Diagram'), ('document', 'Reference Document'), ('chat', 'Chat Export'), ('email', 'Email Thread'), ('recording', 'Call Recording Transcript')], max_length=30),
        ),
    ]
