# Generated by Django 6.0.5 on 2026-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectasset_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentoutput',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether this output has been indexed to the RAG knowledge base'),
        ),
        migrations.AddField(
            model_name='agentoutput',
            name='rag_chunk_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of chunks stored in ChromaDB for this output', null=True),
        ),
        migrations.AddField(
            model_name='agentoutput',
            name='rag_indexed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this output was indexed to RAG', null=True),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='connector_type',
            field=models.CharField(choices=[('mom', 'Minutes of Meeting'), ('drafts', 'Draft BRD Document'), ('url', 'Reference URL'), ('architecture', 'Architecture / Design Diagram'), ('document', 'Reference Document'), ('chat', 'Chat Export'), ('email', 'Email Thread'), ('recording', 'Call Recording Transcript')], max_length=30),
        ),
    ]
