# Generated by Django 5.2.15 on 2026-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rag_indexing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='connector_type',
            field=models.CharField(choices=[('mom', 'Minutes of Meeting'), ('drafts', 'Draft BRD Document'), ('url', 'Reference URL'), ('architecture', 'Architecture / Design Diagram'), ('document', 'Reference Document'), ('chat', 'Chat Export'), ('email', 'Email Thread'), ('recording', 'Call Recording Transcript')], max_length=30),
        ),
    ]
