# Generated by Django 5.2.15 on 2026-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragdocument',
            new_name='rag_ragdocu_status_889abe_idx',
            old_name='rag_ragdocu_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ragdocument',
            new_name='rag_ragdocu_source_12ced1_idx',
            old_name='rag_ragdocu_source_idx',
        ),
        migrations.AlterField(
            model_name='ragdocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'Text'), ('xlsx', 'Excel'), ('xls', 'Excel 97-2003'), ('csv', 'CSV')], help_text='File type/extension', max_length=10),
        ),
    ]
