# Generated by Django 5.2.15 on 2026-07-14 07:51

import apps.ai_chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessionid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='ai_chat_cha_user_id_a3df4d_idx',
            old_name='ai_chat_conv_user_idx',
        ),
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='ai_chat_cha_is_acti_623d3a_idx',
            old_name='ai_chat_cha_is_act_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chat_cha_convers_097a15_idx',
            old_name='ai_chat_cha_conver_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chat_cha_role_f8f683_idx',
            old_name='ai_chat_cha_role_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsessionlog',
            new_name='ai_chat_cha_user_id_78e11b_idx',
            old_name='ai_chat_log_user_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsessionlog',
            new_name='ai_chat_cha_event_t_31f553_idx',
            old_name='ai_chat_log_event_idx',
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='model_used',
            field=models.CharField(default=apps.ai_chat.models.get_default_model, help_text='Azure OpenAI model used (gpt-5.5, gpt-4o, etc)', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_chat.chatsession'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='ai_chat_cha_user_id_9d04df_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['sessionid'], name='ai_chat_cha_session_ed3200_idx'),
        ),
    ]
