"""
BRD Agent

Generates a comprehensive Business Requirements Document with all 11 required sections
from the project description and the user's answers to clarification questions.

Automatically infers and applies industry-specific compliance requirements.
"""

from agents.base import generate_json

SYSTEM_PROMPT_TEMPLATE = """You are a senior business analyst and technical writer specializing in 
enterprise Business Requirements Documents (BRDs).

Your task is to generate a comprehensive, professional BRD in valid JSON format.

The BRD must ONLY include the specific sections requested in the JSON format below. Do not add or omit any requested section.

IMPORTANT RULES:
- Infer and apply relevant compliance standards from the project context.
- Adhere strictly to the format, tone, and guidance provided in the <COMPANY_KNOWLEDGE_BASE> block (if provided).
- Make all requirements SMART.
- If generating functional requirements, every functional requirement must have a unique ID (FR-001). CRITICAL: LIMIT to EXACTLY top 8-10 functional requirements. Do NOT generate more than 10.
- If generating non-functional requirements, every non-functional requirement must have a unique ID (NFR-001). CRITICAL: LIMIT to EXACTLY 5 non-functional requirements.
- If generating a glossary, the glossary MUST be limited to a MAXIMUM of 3 terms.
- Test cases and effort estimation will be generated by separate agents later.
- Return ONLY valid JSON. No markdown fences, no preamble, no commentary.
- Be extremely concise in your text descriptions. Your output is hard-capped at 8000 tokens and you WILL be cut off if you generate too much text. Keep descriptions under 2 sentences.

Required JSON format:
{json_shape}
"""

STANDARD_SCHEMAS = {
    "executive_summary": '"2-3 paragraph summary of the project, business context, and expected outcomes"',
    "project_scope": """{
    "in_scope": ["item 1", "item 2"],
    "out_of_scope": ["item 1", "item 2"]
  }""",
    "current_state_analysis": '"Detailed analysis of the current state, systems, and processes"',
    "business_objectives": """[
    {
      "id": "BO-001",
      "objective": "...",
      "metric": "How success will be measured",
      "target": "Specific target value"
    }
  ]""",
    "functional_requirements": """[
    {
      "id": "FR-001",
      "title": "...",
      "description": "...",
      "priority": "Must Have|Should Have|Could Have|Won't Have",
      "acceptance_criteria": ["criterion 1", "criterion 2"],
      "compliance_notes": "Any relevant compliance standards (or 'N/A')"
    }
  ]""",
    "non_functional_requirements": """[
    {
      "id": "NFR-001",
      "category": "Performance|Security|Scalability|Usability|Availability|Compliance",
      "requirement": "...",
      "metric": "Specific measurable target",
      "priority": "Must Have|Should Have|Could Have"
    }
  ]""",
    "integration_requirements": """[
    {
       "system": "...",
       "integration_type": "API|Batch|Webhook",
       "description": "..."
    }
  ]""",
    "assumptions_and_dependencies": """{
    "constraints": [
      {
        "id": "CON-001",
        "description": "...",
        "impact": "..."
      }
    ],
    "assumptions": [
      {
        "id": "ASS-001",
        "description": "...",
        "risk_if_wrong": "..."
      }
    ]
  }""",
    "risks_and_mitigations": """[
    {
      "id": "RSK-001",
      "description": "...",
      "probability": "High|Medium|Low",
      "impact": "High|Medium|Low",
      "mitigation": "..."
    }
  ]""",
    "stakeholders": """[
    {
      "role": "...",
      "responsibilities": "...",
      "interest_level": "High|Medium|Low",
      "influence_level": "High|Medium|Low"
    }
  ]""",
    "project_plan": """{
    "phases": [
      {
        "phase": "Phase 1 - Discovery & Requirements",
        "duration": "2 weeks",
        "deliverables": ["..."],
        "milestones": ["..."]
      }
    ]
  }""",
    "effort_estimation": """{
    "total_estimated_hours": 0,
    "summary": "High-level effort breakdown",
    "breakdown": [
      {
        "component": "...",
        "hours": 0,
        "complexity": "Low|Medium|High"
      }
    ]
  }""",
    "success_criteria": """[
    {
      "id": "SC-001",
      "criterion": "...",
      "measurement_method": "...",
      "target": "..."
    }
  ]""",
    "sign_off_matrix": """[
    {
      "role": "...",
      "name": "...",
      "sign_off_date": "YYYY-MM-DD"
    }
  ]""",
    "glossary": """[
    {
      "term": "...",
      "definition": "..."
    }
  ]"""
}

# Alias for backwards compatibility if needed
STANDARD_SCHEMAS["constraints_and_assumptions"] = STANDARD_SCHEMAS["assumptions_and_dependencies"]

def generate_brd(
    project_description: str,
    clarification_answers: dict | None = None,
    revision_notes: str | None = None,
    context_summary: str | None = None,
    company_knowledge_base: str | None = None,
    toc_sections: list[dict] | None = None,
) -> dict:
    """
    Generate a full BRD JSON document from the project description and answers.

    Args:
        project_description: Extracted text from user input or uploaded file.
        clarification_answers: Dict mapping question IDs to user answers.
        revision_notes: Optional notes if user requested a revision.
        context_summary: Text from extracted assets.
        company_knowledge_base: Extracted knowledge base RAG context.
        toc_sections: Optional list of dictionaries describing the requested TOC sections.

    Returns:
        dict: Full BRD structured output with only the requested sections.

    Raises:
        ValueError: If the AI response cannot be parsed as JSON.
        RuntimeError: If the AI API call fails.
    """
    # Build dynamic JSON schema
    schema_parts = []
    
    if toc_sections is None:
        # Fallback to a default structure if not provided
        keys = ["executive_summary", "project_scope", "business_objectives", "stakeholders", 
                "project_plan", "effort_estimation", "functional_requirements", 
                "non_functional_requirements", "constraints_and_assumptions", 
                "success_criteria", "glossary"]
        toc_sections = [{"key": k, "label": k.replace('_', ' ').title()} for k in keys]
        
    for sec in toc_sections:
        key = sec['key']
        if key in STANDARD_SCHEMAS:
            schema_parts.append(f'  "{key}": {STANDARD_SCHEMAS[key]}')
        else:
            label = sec.get('label', key.replace('_', ' ').title())
            schema_parts.append(f'''  "{key}": {{
    "content_blocks": [
      {{
        "type": "paragraph",
        "text": "Detailed explanation for {label}"
      }},
      {{
        "type": "list",
        "items": ["Important point 1", "Important point 2"]
      }},
      {{
        "type": "table",
        "headers": ["Metric", "Value"],
        "rows": [["Data", "Data"]]
      }}
    ]
  }}''')
            
    json_shape = "{\n" + ",\n".join(schema_parts) + "\n}"
    
    system_prompt = SYSTEM_PROMPT_TEMPLATE.replace('{json_shape}', json_shape)

    answers_section = ''
    if clarification_answers:
        answers_section = '\n\nUser Answers to Clarification Questions:\n'
        for q_id, answer in clarification_answers.items():
            answers_section += f'  {q_id}: {answer}\n'

    revision_section = ''
    if revision_notes:
        revision_section = f'\n\nRevision Notes from Stakeholder:\n{revision_notes}'

    context_section = ''
    if context_summary and context_summary.strip():
        context_section = f'\n\n{context_summary}'

    knowledge_base_section = ''
    if company_knowledge_base and company_knowledge_base.strip():
        knowledge_base_section = f'\n\n{company_knowledge_base}'

    user_prompt = f"""Project Description:
{project_description}
{answers_section}
{revision_section}
{context_section}
{knowledge_base_section}

Generate a comprehensive BRD focusing ONLY on the requested sections in the schema."""

    return generate_json(system_prompt, user_prompt)
