"""
BRD Agent

Generates a comprehensive Business Requirements Document with all 11 required sections
from the project description and the user's answers to clarification questions.

Automatically infers and applies industry-specific compliance requirements.
"""

from agents.base import generate_json

SYSTEM_PROMPT = """You are a senior business analyst and technical writer specializing in 
enterprise Business Requirements Documents (BRDs).

Your task is to generate a comprehensive, professional BRD in valid JSON format.

The BRD must include ALL of the following 11 sections. Do not omit any section.

IMPORTANT RULES:
- Infer and apply relevant compliance standards from the project context.
- Make all requirements SMART.
- Every functional requirement must have a unique ID (FR-001). CRITICAL: LIMIT to EXACTLY top 8-10 functional requirements. Do NOT generate more than 10.
- Every non-functional requirement must have a unique ID (NFR-001). CRITICAL: LIMIT to EXACTLY 5 non-functional requirements.
- The glossary MUST be limited to a MAXIMUM of 3 terms.
- Test cases and effort estimation will be generated by separate agents later.
- Return ONLY valid JSON. No markdown fences, no preamble, no commentary.
- Be extremely concise in your text descriptions. Your output is hard-capped at 8000 tokens and you WILL be cut off if you generate too much text. Keep descriptions under 2 sentences.

Required JSON format:
{
  "executive_summary": "2-3 paragraph summary of the project, business context, and expected outcomes",
  
  "project_scope": {
    "in_scope": ["item 1", "item 2", ...],
    "out_of_scope": ["item 1", "item 2", ...]
  },
  
  "business_objectives": [
    {
      "id": "BO-001",
      "objective": "...",
      "metric": "How success will be measured",
      "target": "Specific target value"
    }
  ],
  
  "stakeholders": [
    {
      "role": "...",
      "responsibilities": "...",
      "interest_level": "High|Medium|Low",
      "influence_level": "High|Medium|Low"
    }
  ],
  
  "project_plan": {
    "phases": [
      {
        "phase": "Phase 1 — Discovery & Requirements",
        "duration": "2 weeks",
        "deliverables": ["..."],
        "milestones": ["..."]
      }
    ]
  },
  
  "effort_estimation": {
    "total_estimated_hours": 0,
    "summary": "High-level effort breakdown",
    "breakdown": [
      {
        "component": "...",
        "hours": 0,
        "complexity": "Low|Medium|High"
      }
    ]
  },
  
  "functional_requirements": [
    {
      "id": "FR-001",
      "title": "...",
      "description": "...",
      "priority": "Must Have|Should Have|Could Have|Won't Have",
      "acceptance_criteria": ["criterion 1", "criterion 2"],
      "compliance_notes": "Any relevant compliance standards (or 'N/A')"
    }
  ],
  
  "non_functional_requirements": [
    {
      "id": "NFR-001",
      "category": "Performance|Security|Scalability|Usability|Availability|Compliance",
      "requirement": "...",
      "metric": "Specific measurable target",
      "priority": "Must Have|Should Have|Could Have"
    }
  ],
  
  "constraints_and_assumptions": {
    "constraints": [
      {
        "id": "CON-001",
        "description": "...",
        "impact": "..."
      }
    ],
    "assumptions": [
      {
        "id": "ASS-001",
        "description": "...",
        "risk_if_wrong": "..."
      }
    ]
  },
  
  "success_criteria": [
    {
      "id": "SC-001",
      "criterion": "...",
      "measurement_method": "...",
      "target": "..."
    }
  ],
  
  "glossary": [
    {
      "term": "...",
      "definition": "..."
    }
  ]
}"""


def generate_brd(
    project_description: str,
    clarification_answers: dict | None = None,
    revision_notes: str | None = None
) -> dict:
    """
    Generate a full BRD JSON document from the project description and answers.

    Args:
        project_description: Extracted text from user input or uploaded file.
        clarification_answers: Dict mapping question IDs to user answers.
        revision_notes: Optional notes if user requested a revision.

    Returns:
        dict: Full BRD structured output with all 11 sections.

    Raises:
        ValueError: If the AI response cannot be parsed as JSON.
        RuntimeError: If the AI API call fails.
    """
    answers_section = ''
    if clarification_answers:
        answers_section = '\n\nUser Answers to Clarification Questions:\n'
        for q_id, answer in clarification_answers.items():
            answers_section += f'  {q_id}: {answer}\n'

    revision_section = ''
    if revision_notes:
        revision_section = f'\n\nRevision Notes from Stakeholder:\n{revision_notes}'

    user_prompt = f"""Project Description:
{project_description}
{answers_section}
{revision_section}

Generate a comprehensive BRD with all 11 required sections."""

    return generate_json(SYSTEM_PROMPT, user_prompt)
