# Generated by Django 5.2.15 on 2026-07-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial_userprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='authenticat_role_4d1409_idx',
            old_name='auth_userpr_role_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='authenticat_is_acti_4dfe8d_idx',
            old_name='auth_userpr_is_act_idx',
        ),
    ]
